config/routes.rb
Rails.application.routes.draw do


  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end

  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#home' #change back to pages#about
  get 'treatments', to: 'pages#home' #change back to pages#treatments
  get 'contact', to: 'pages#home' #change back to pages#contact
  get 'shop', to: 'pages#home' #change back to pages#shop
  get 'faqs', to: 'pages#home' #change back to pages#faqs
  get 'booking', to: 'pages#home' #change back to pages#booking
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  monetize :amount_pennies
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  monetize :price_pennies
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # , :set_promotion

  private

  # def set_promotion
  #   @promotion = Treatment.first
  # end
end

app/controllers/orders_controller.rb
# class OrdersController < ApplicationController
#   skip_before_action :authenticate_user!

#   def show
#     @order = Order.where(state: 'paid').find(params[:id])
#   end

#   def create
#     @treatment = Treatment.find(params[:treatment_id])
#     order = Order.create!(sku: @treatment.sku, amount: @treatment.price, state: 'pending')

#     redirect_to new_order_payment_path(order)
#   end
# end

app/controllers/pages_controller.rb
require 'open-uri'
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :instagram, only: [:home, :about, :treatments, :contact]

  def home
  end

  def about
  end

  def treatments
  end

  def contact
  end

  def faqs
  end

  # def shop
  #   @treatments = Treatment.all
  # end

  def booking
  end

  private

  def instagram
    url = "https://api.instagram.com/v1/users/self/media/recent/?access_token=4180675608.edb0eb8.66852b5861f24b8fbb9e1d7dac7fedc6"
    media = JSON.parse(open(url).read)["data"]
    @image_urls = []
    media.first(10).each do |media|
      @image_urls << media["link"]
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_order

  def new
  end

  def create
    customer = Stripe::Customer.create(
      source: params[:stripeToken],
      email:  params[:stripeEmail]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount:       @order.amount_pennies,
      description:  "Payment for treatment #{@order.sku} for order #{@order.id}",
      currency:     @order.amount.currency
    )

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to order_path(@order)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_order_payment_path(@order)
  end

  private

  def set_order
    @order = Order.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/treatments_controller.rb
# class TreatmentsController < ApplicationController
#   skip_before_action :authenticate_user!

#   def index
#   end

#   def show
#   end

# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head><%= favicon_link_tag 'TPB_favicon.ico' %>
    <title>The Peel Boutique</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-103992723-1', 'auto');
      ga('send', 'pageview');

    </script>
  </head>
  <body>
    <%= render 'shared/flashes' %>
      <%= flash[:error] %>
      <%= flash[:notice] %>
    </div>
    <%= yield %>

    <div class="modal fade promotion-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <%= render "shared/promotion" %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/show.html.erb
<h1 style="margin-top: 100px;">Booking Confirmation</h1>
<ul>
  <li>Status: <%= @order.state %></li>
  <li>Item: <%= @order.sku %></li>
  <li>Amount: <%= humanized_money_with_symbol(@order.amount) %></li>
<ul>

app/views/pages/about.html.erb
<%= render 'shared/navbar' %>
<div class="homepage-banner" style="background-image: url('http://res.cloudinary.com/dc8wyadoa/image/upload/v1493745930/ContactBanner_dfskmz.jpg');">
</div>
<div class="page-content">
	<div class="about-sub-text text-center">
		<h3>ABOUT US</h3>
		<p>DR RABIA MALIK is a sought after aesthetic medical doctor who specialises in non-invasive, non-surgical facial rejunenation and problem skin solutions. Her holistic approach to skincare, focusing on custom made chirally correct compositions makes her unique.
		<br></br>
		The foundation for Dr. Malik's word is facial skin peels, which are still one of the best optoins for a healthier, vibrant complexion. However, unlike so many chemical peels on the market, Dr. Malik works with less invasive peels that don't dtrip the skin or leave it inflamed and irritated. Instead she strived to provide her patients with the peels that offer minimum downtime and maxiumum results whilte remaining chirally correct.</p>
		<div class="about-rabia-image">
			<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493732556/About_rabia_o5qwvo.jpg
			") %>
		</div>
		<p>Chirality refers to products that are chemically correct for the skin, and only contain the molecule that is right for the skin's receptors. Dr. Malik works with various formulations custom made for her in the US to create combination skin peels that are chemically built for fluency with the skin's molecule receptors. If skin care products are not chemically correct to fit into the skin's receptors then the product simply won't work or they can increase aging and disease. Chemically correct products penetrate the skin and skin cells so that the ingredients can arrive to cause positive change.
		<br></br>
		Dr. Malik began her aesthetic medical practice 5 years ago and has been practicing at Grace Medical for over 3 years. During this time, Dr. Malik became concerned that her patients needed a high quality, chirally correct maintenance treatment to tie them over between more intensive peels. However, there was no such treatment on the market and so the idea of The Peel Boutique – a gentler non-medical skin maintenance treatment – was born.</p>
		<div class="about-small-images">
			<div class="about-small-image">
				<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493732729/About1_o5vtd4.jpg") %>
			</div>
			<div class="about-small-image">
				<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493749349/press_evxmuq.jpg") %>
			</div>
		</div>
		<p>The idea of chemical peels suggests intrusive use of harsh ingredients like Glycolic Acid, yet Dr. Malik's peels are lactic acid based and therefore kinder on the skin while still achieving the best results. While creating this safe peel, Dr. Malik was also aware that this needed to be an express treatment, carried out by specially trained therapists, to fit easily into busy lifestyles – minimum downtime and maxiumum results.</p>
	</div>
	<%= render 'shared/instagram_section' %>
	<%= render 'shared/footer' %>
</div>

app/views/pages/booking.html.erb
<%= render 'shared/navbar' %>
<div class="main-container container text-center">
	<div class="booking-header text-center">
		<h3>BOOK A TREATMENT</h3>
	</div>
	<div class="date-pick container text-center">
		<script src="https://widgets.healcode.com/javascripts/healcode.js" type="text/javascript"></script>

		<healcode-widget data-type="appointments" data-widget-partner="object" data-widget-id="6122928c14d" data-widget-version="0.1"></healcode-widget>
	</div>
</div>
 <%= render 'shared/footer' %>

app/views/pages/home.html.erb
<%= render 'shared/navbar_landing' %>
<div class="homepage">
	<div class="homepage-banner hidden-xs hidden-sm hidden-md" style="background-image: url('http://res.cloudinary.com/dc8wyadoa/image/upload/v1493941438/Screen_Shot_2017-05-05_at_00.43.11_f23ikq.png')">
		<div class="holding-text-lg">
			<p><span>New London Location Coming Soon.</p></span>
			<p>For all enquires please email <%= link_to "info@thepeelboutique.com", "mailto:info@thepeelboutique.com" %></p>
		</div>
		<div class="banner-content">
	    	<%= image_tag "TPB-logo-big.png", class: "main-logo fadeIn landing-logo" %>
	  	</div>
	</div>
	<div class="homepage-banner hidden-lg hidden-xl" style="background-image: url('http://res.cloudinary.com/dc8wyadoa/image/upload/v1493986903/LAnding_image_igyjxu.jpg')">
		<div class="holding-text-md">
			<p><span>New London Location Coming Soon.</p></span>
			<p>For all enquires please email <%= link_to "info@thepeelboutique.com", "mailto:info@thepeelboutique.com" %></p>
		</div>
		<div class="banner-content">
	    	<%= image_tag "TPB-logo-big.png", class: "main-logo fadeIn landing-logo" %>
	  	</div>
	</div>
	<div class="homepage-banner hidden-sm hidden-md hidden-lg hidden-xl" style="background-image: url('http://res.cloudinary.com/dc8wyadoa/image/upload/v1493987182/mobile_landing_pfdj4n.jpg')">
		<div class="banner-content">
	    	<%= image_tag "TPB-logo-big.png", class: "main-logo fadeIn landing-logo" %>
	  	</div>
	</div>
	<%= link_to "", class: "enter-btn" do %>
	<div class="landing-page-content pullUp">
		<div class="landing-sub-text text-center hidden-xs" id="enter">
			<p>Visibly brighter, healthier looking skin</p>
			<!-- change back <i class="fa fa-arrow-down enter-btn"></i>-->
		</div>
		<div class="landing-sub-text text-center hidden-lg hidden-md hidden-sm" id="enter" style="display: flex; flex-direction: column; justify-content: center;align-items: center;">
			<p style="width: 325px">New London Location Coming Soon.</p>
			<p>For all enquires please email <%= link_to "info@thepeelboutique.com", "mailto:info@thepeelboutique.com" %></p>
		</div>
	<% end %>




</div>

<!-- change back

	<div class="intro-text text-center container" id="landing-content">
		<p><strong>THE PEEL BOUTIQUE</strong> offers an express treatment of high-quality professional strength lactic acid skin peels that are chirally correct and non-inflammatory or skin thinning.
		</p>
	</div>
		<div class="landing-boxes">
			<div class="landing-treatments-box">
        <%= image_tag "http://res.cloudinary.com/dc8wyadoa/image/upload/v1490786000/TPB-strip-blue_t8fnpz.png", class: "landing-strip landing-strip-left" %>
				<h3 class="text-center">TREATMENTS</h3>
				<p>Choose from 3 bespoke face feels on The Peel Boutique menu to cater for all skin types and colours.
				<br></br>
				&nbsp;<%= link_to "– THE BRIGHTENING PEEL", treatments_path(:anchor => "treatment-menu") %><br>
				&nbsp;<%= link_to "– THE HYDRATING PEEL", treatments_path(:anchor => "treatment-menu") %><br>
				&nbsp;<%= link_to "– THE BLEMISH PEEL", treatments_path(:anchor => "treatment-menu") %><br>
				<br>
				<%= link_to "READ MORE...", treatments_path %></p>
			</div>
			<div class="landing-treatments-image">
        <%= image_tag "http://res.cloudinary.com/dc8wyadoa/image/upload/v1490786000/TPB-strip-blue_t8fnpz.png", class: "landing-strip landing-strip-right" %>
				<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493752083/Landing-treatments_kqzocm.jpg", id: "treatments-image") %>
			</div>
		</div>
		<div class="text-center hidden-sm hidden-xs">
			<%= link_to "BOOK A TREATMENT", "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request", class: "pink-btn" %>
		</div>
		<div class="text-center hidden-md hidden-lg hidden-xl">
			<%= link_to "BOOK A TREATMENT", "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request", class: "pink-btn-small" %>
		</div>
		<div class="landing-boxes-about">
			<div class="landing-about-image">
        <%= image_tag "http://res.cloudinary.com/dc8wyadoa/image/upload/v1490786000/TPB-strip-blue_t8fnpz.png", class: "landing-strip landing-strip-left-2" %>
        <div id="about-image">
				  <%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1495030898/The_Peel_Boutique_About_Rabia.jpg") %>
        </div>
			</div>
			<div class="landing-about-box">
        <%= image_tag "http://res.cloudinary.com/dc8wyadoa/image/upload/v1490786000/TPB-strip-blue_t8fnpz.png", class: "landing-strip landing-strip-right-2" %>
				<h3 class="text-center">ABOUT US</h3>
				<p>DR. RABIA MALIK is a sought after aesthetic medical doctor who specialises in non-invasive, non-surgical facial rejuvenation and problem skin solutions. She believes in a holistic approach to skincare to achieve a healthier and vibrant complexion.<br>
				<br>
				<%= link_to "READ MORE...", about_path %></p></p>
			</div>
		</div>
		<div class="spacer-text text-center">
			<h3>FIRMER, LIFTED, MORE YOUTHFUL LOOKING SKIN</h3>
		</div>
		<div class="landing-boxes">
			<div class="landing-book-box">
				<%= link_to "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request" do %>
	 				<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493751408/Shop_deqcq5.jpg") %>
					<p>BOOK <br>TREATMENT</p>
					<div class="triangle-pink-box"></div>
				<% end %>
			</div>
			<div class="landing-shop-box">
					<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493749479/Shop_uqyepb.jpg") %>
					<p id="shop-products">SHOP <br>PRODUCTS</p>
					<p id="coming-soon">COMING SOON</p>
					<div class="triangle-pink-box"></div>
				</div>
			</div>
			<div class="landing-boxes">
				<div class="triple-box landing-press-image">
		 				<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493752265/press1_vsqug9.jpg") %>
						<p id="press-box">PRESS</p>
						<p id="press-contact">020 7235 8900</p>
				</div>
				<div class="triple-box landing-contact-image">
					<%= link_to contact_path do %>
						<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493728724/Contact_uinhcq.jpg") %>
						<p>CONTACT</p>
					<% end %>
				</div>
				<div class="triple-box landing-faq-image">
					<%= link_to faqs_path do %>
						<%= image_tag("http://res.cloudinary.com/dc8wyadoa/image/upload/v1493951721/press_eqe946.jpg") %>
						<p>FAQs</p>
					<% end %>
				</div>
			</div>
			<div class="spacer-text text-center">
				<h3>NON-TOXIC, REJUVENATING AND PROFESSIONAL PEELS</h3>
			</div>
			<%= render 'shared/instagram_section' %>
			<%= render 'shared/footer' %>
		</div>
	</div>

app/views/pages/shop.html.erb
<%= render 'shared/navbar' %>
<!-- <div class="treatments" style="margin-top: 100px; margin-left: 40px;">
  <% @treatments.each do |treatment| %>
    <h3><%= treatment.name %></h3>
    <p><%= treatment.description %></p>
    <p>Price: <%= humanized_money_with_symbol(treatment.price) %></p>
    <%= form_tag orders_path do %>
      <%= hidden_field_tag 'treatment_id', treatment.id %>
      <%= submit_tag 'Book', class: 'btn btn-info' %>
    <% end %>
  <% end %>
</div> -->

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/new.html.erb
<h1 style="margin-top: 100px;">Purchase of treatment <%= @order.sku %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Treatment"
    data-description="<%= @order.sku %>"
    data-amount="<%= @order.amount_pennies %>"
    data-currency="<%= @order.amount.currency %>"></script>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
	<div class="footer-main text-center">
		<%= image_tag "TPB-logo-big-white.png", class: "footer-logo" %>
		<p> Grace Belgravia Medical<br>
			11a West Halkin Street<br>
			London<br>
			SW1X 8JL<br>
			<br>
			<%= link_to "thepeelboutique@gracebelgravia.com ", "mailto:thepeelboutique@gracebelgravia.com " %><br>
			<br>
			<%= link_to "https://www.instagram.com/thepeelboutique/?hl=en", target: "_blank" do %>
  				<i class="fa fa-instagram"></i>
			<% end %>&nbsp; 
			<%= link_to "https://www.facebook.com/search/photos/?q=%40thepeelboutique", target: "_blank" do %>
  				<i class="fa fa-facebook"></i>
			<% end %>&nbsp; 
			<%= link_to "https://twitter.com/hashtag/thepeelboutique?f=tweets&vertical=default&src=hash&lang=en", target: "_blank" do %>
  				<i class="fa fa-twitter"></i>
			<% end %>
		</p>
	</div>
	<!-- <div class="sign-up">
		<script src="https://widgets.healcode.com/javascripts/healcode.js" type="text/javascript"></script>
		<healcode-widget data-type="prospects" data-widget-partner="object" data-widget-id="6121360c14d" data-widget-version="0.1"></healcode-widget>
		<div class="box hidden-sm hidden-xs"></div>
	</div> -->
	<div class="footer-small text-center">
		<p><%= link_to "FAQs", faqs_path %> &nbsp;| &nbsp;
		© The Peel Boutique <%= Date.current.year %> &nbsp;| &nbsp; <%= link_to "Site Credits", "http://www.mouse-code.com/", target: "_blank" %></p>
	</div>
</div>

app/views/shared/_instagram_section.html.erb
<div class="instagram-section">
  <div class="instagram-wrapper">
    <% @image_urls.each do |url| %>
      <%= link_to "https://www.instagram.com/thepeelboutique/", target: '_blank' do %>
        <div class="insta-img">
          <img src=<%= "#{url}media/"%>>
          <div class="insta">
            <p>@thepeelboutique</p>
          </div>
          <div class="insta-box"></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-the-peel-boutique-main navbar-the-peel-boutique-main-fixed hidden-xs hidden-sm">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-the-peel-boutique-main-brand" do %>
    <%= image_tag "TPB-logo-big-pink.png", class: "pink-logo" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-the-peel-boutique-main-right">

<!-- Navbar menu -->
   <!-- About link -->
    <div class="navbar-link">
      <%= link_to "ABOUT US", about_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
    <!-- Treatments link -->
    <div class="navbar-link">
      <%= link_to "TREATMENTS", treatments_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
    <!-- Contact link -->
    <div class="navbar-link">
      <%= link_to "CONTACT", contact_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
      <!-- Shop  link -->
    <div class="navbar-link shop-link">
      <%= link_to "SHOP", "", class: "navbar-the-peel-boutique-main-link shop-link" %>
    </div>
      <!-- FAQs link -->
    <div class="navbar-link">
      <%= link_to "FAQs", faqs_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
  </div>
      <!--<div class="promotion-btn" data-toggle="modal" data-target=".promotion-modal">PROMOTION</div>-->

  <%= link_to "BOOK NOW", "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request", class: "booking-btn" %>
</div>



<!-- Dropdown list appearing on mobile only BEFORE SCROLL-->
<div class="navbar-the-peel-boutique-main navbar-the-peel-boutique-main-fixed hidden-md hidden-lg">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-the-peel-boutique-main-brand" do %>
    <%= image_tag "TPB-logo-big-pink.png" %>
  <% end %>
  <div class="navbar-the-peel-boutique-main-item hidden-md hidden-lg">
    <div class="dropdown">
      <a class="fa fa-bars dropdown-toggle" data-toggle="dropdown" href="#"></a>
      <ul class="dropdown-menu dropdown-menu-right navbar-the-peel-boutique-main-dropdown-menu">
        <li><%= link_to "ABOUT US", about_path %></li>
        <li><%= link_to "TREATMENTS", treatments_path %></li>
        <li><%= link_to "CONTACT", contact_path %></li>
        <li><%= link_to "FAQs", faqs_path %></li>
        <li><%= link_to "BOOK NOW", "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_landing.html.erb
<div class="navbar-the-peel-boutique-main-landing  navbar-the-peel-boutique-main-fixed hidden-xs hidden-sm">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-the-peel-boutique-main-brand-landing" do %>
    <%= image_tag "TPB-logo-small.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-the-peel-boutique-main-right">

<!-- Navbar menu -->
   <!-- About link -->
    <div class="navbar-link">
      <%= link_to "ABOUT US", about_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
    <!-- Treatments link -->
    <div class="navbar-link">
      <%= link_to "TREATMENTS", treatments_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
    <!-- Contact link -->
    <div class="navbar-link">
      <%= link_to "CONTACT", contact_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
      <!-- Shop  link -->
    <div class="navbar-link">
      <%= link_to "SHOP", "", class: "navbar-the-peel-boutique-main-link shop-link" %>
    </div>
      <!-- FAQs link -->
    <div class="navbar-link">
      <%= link_to "FAQs", faqs_path, class: "navbar-the-peel-boutique-main-link" %>
    </div>
  </div>
  <!-- <div class="promotion-btn" data-toggle="modal" data-target=".promotion-modal">PROMOTION</div>-->



  <%= link_to "BOOK NOW", "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request", class: "booking-btn" %>
</div>
<div class="opening-hours">
  <p>Opening Hours: 8am – 8pm Mon – Fri / 9am – 7pm Sat & Sun</p>
</div>

<!-- CHANGE BACK FROM HIDDEN -->

<!-- Dropdown list appearing on mobile only BEFORE SCROLL-->
<div class="navbar-the-peel-boutique-main navbar-the-peel-boutique-main-fixed hidden hidden-md hidden-lg">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-the-peel-boutique-main-brand" do %>
    <%= image_tag "TPB-logo-small.png" %>
  <% end %>
  <div class="navbar-the-peel-boutique-main-item hidden-md hidden-lg">
    <div class="dropdown toggle-white">
      <a class="fa fa-bars dropdown-toggle" data-toggle="dropdown" href=""></a>
      <ul class="dropdown-menu dropdown-menu-right navbar-the-peel-boutique-main-dropdown-menu">
        <li><%= link_to "ABOUT US", about_path %></li>
        <li><%= link_to "TREATMENTS", treatments_path %></li>
        <li><%= link_to "CONTACT", contact_path %></li>
        <li><%= link_to "FAQs", faqs_path %></li>
        <li><%= link_to "BOOK NOW", "mailto:thepeelboutique@gracebelgravia.com?subject=The Peel Boutique Booking Request" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/treatments/_index.html.erb
<div class="treatments">
  <% @treatments.each do |treatment| %>
    <h3><%= treatment.name %></h3>
    <p><%= treatment.description %></p>
</div>

app/views/treatments/index.html.erb
<div class="treatments" style="margin-top: 100px; margin-left: 40px;">
  <% @treatments.each do |treatment| %>
    <h3><%= treatment.name %></h3>
    <p><%= treatment.description %></p>
    <p>Price: <%= humanized_money_with_symbol(treatment.price) %></p>

  <% end %>
</div>

app/views/treatments/show.html.erb
<h1>Treatments#show</h1>
<p>Find me in app/views/treatments/show.html.erb</p>